# Site settings
author: Vanessa Fotso
title: Breaking into Technology
header-img: img/home-bg.png
email: vanessuniq@gmail.com
copyright_name: Vanessa Fotso
description: > # this means to ignore newlines until "baseurl:"
  Software engineering immersion
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vanessuniq

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
